version: '3.9'

services:
  backend:
    image: alenamelnikova/backend-app:latest
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend-app:/app
    env_file:
      - ./backend-app/.env
    depends_on:
      - db

  frontend:
    image: alenamelnikova/frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - frontend_static:/app/result_build

  db:
    image: postgres:15
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: calories
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    env_file: backend-app/.env
    ports:
      - '8080:80'
    restart: unless-stopped
    volumes:
      - frontend_static:/usr/share/nginx/html/
    depends_on:
      - backend

volumes:
  postgres_data:
  frontend_static:
