version: '3.9'

services:
  backend:
    build: ./backend-app
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend-app:/app
    env_file:
      - ./backend-app/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: calories
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
