name: Deploy Frontend to Dev

on:
  workflow_run:
    workflows: ["Build and Push Frontend Image"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy frontend from Docker Hub to Dev Server
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_KEY }}

      - name: Deploy frontend on dev server
        run: |
          ssh -o StrictHostKeyChecking=no root@89.104.66.61 << 'EOF'
            docker pull alenamelnikova/frontend:latest

            docker stop frontend || true
            docker rm frontend || true

            docker run -d \
              --name frontend \
              -p 8080:80 \
              alenamelnikova/frontend:latest
          EOF
