name: diploma deploy

on: push

jobs:
  build_frontend_and_push_to_docker_hub:
    name: Push frontend Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: alenamelnikova/frontend:latest
  
  build_backend_and_push_to_docker_hub:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    needs: build_frontend_and_push_to_docker_hub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }} 
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./backend-app/
          push: true
          tags: alenamelnikova/backend-app:latest

  deploy:
    name: Deploy from Docker Hub to Dev Server
    runs-on: ubuntu-latest
    needs: build_backend_and_push_to_docker_hub
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_KEY }}

      - name: Deploy backend on dev server
        run: |
          ssh -o StrictHostKeyChecking=no root@89.104.66.61 << 'EOF'
            cd diploma
            sudo docker compose -f docker-compose.dev.yml pull
            sudo docker compose -f docker-compose.dev.yml down
            sudo docker compose -f docker-compose.dev.yml up -d
            sudo docker compose -f docker-compose.dev.yml exec backend python manage.py migrate
          EOF

  send_message:
    name: Send message to Telegram
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} успешно выполнен. ${{ github.actor }} выполнил(а) коммит - "${{ github.event.commits[0].message }}"